waypoints:
  - position:
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - position:
      x: 6.0
      y: 4.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.2588190451025207
      w: 0.9659258262890683
  - position:
      x: 6.5
      y: -1.4
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0
  - position:
      x: -1.6
      y: -2.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.6087614290087207
      w: 0.7933533402912352
  - position:
      x: 8.0
      y: -4.65
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - position:
      x: 8.0
      y: 4.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - position:
      x: 7.0
      y: 0.2
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - position:
      x: -5.0
      y: 3.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - position:
      x: -5.0
      y: -3.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
